version: '3.8'

services:
  # Node.js
  app:
    build: ./api3
    ports:
      - "8003:8003"
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=ASIAVYOMUIQSXVOO34M6
      - AWS_SECRET_ACCESS_KEY=zPY+jj9TgJA91kammmeNFRok0B6KntmSdzPHecHF
      - AWS_SESSION_TOKEN=IQoJb3JpZ2luX2VjEEcaCXVzLXdlc3QtMiJHMEUCIFkxNtUvumcxStPxgkjjsB9BkNpUbgLGaMrhFNuMz4XAAiEAyU70K9p5Uq4/jv4ru+fCLNyPW9lNo4hBhmrzB8CH1+UqpQIIoP//////////ARABGgwzOTYxMDMwMDkzMTciDO3bucSXt8YqQsLzYyr5Ae1xL09q83cNuHOTr4pevRx1kI5QFqBIVJX/gZbEGGwOOhmTKGqRLXx+PchRemu2tD+d5VMoZKWKGwGBnoYGdmKTOR1ziS3tr2jjwiaRy35FHAt+b96bwKvDCKoYjj5AnsoO3/bnH1f3yxraceWrh9HHdaqeE6GoUhGBX/vvHji+Pz6uAkH+2BKD9NE3ObcWNmkohwQLN/oTPvbv8kOdsrxWhjadgbdjdsOI3hht8ZayBir4TOMarIuFgJtr9HpB5TROKW6zX2ZN8Py0EQCN40aJW9NNaZxw5KN5dgRZOZaYPMZdl6y4CTaDg3dezZmHP3BwftkVLsGRxTCwtai4BjqdAUWT1z/BdEYB8YCHa98LBiQxGHkI7vW7QwrDtdP8dni8BUbqxK7cYwPwbk+G8qCg1p1dv29Zisp6zi6t7tZ5q56hFY8TtB8w/e45dIE+3cLlULh9Be6fYTHggjoh3WpzWSBdDsBgMuyLOoOlV2KcghOlXOkEtyOgTrn2uGSPtc6TLOlQ8qCYoc1yFX+34/gzJ5FX3jFT1qz7+55/P9Q=

      
    networks:
      - my-network

  orquestador:
    build: ./orquestador
    ports:
      - "8001:8001"
    networks:
      - my-network

  # FastAPI
  api1:
    build: ./api1
    ports:
      - "8000:8000"
    environment:
      - DATA_USER=postgres.gwtvzmsuunpikefnnzwn
      - DATA_PASSWORD=L2NFS60u4W7paoPE
      - HOST=aws-0-us-east-1.pooler.supabase.com
      - DB_PORT=5432
      - DATABASE_NAME=bd_1
    networks:
      - my-network

  # Spring Boot
  api2:
    build: ./api2
    ports:
      - "8002:8002"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:5432/bd_2
      - SPRING_DATASOURCE_USERNAME=postgres.gwtvzmsuunpikefnnzwn
      - SPRING_DATASOURCE_PASSWORD=L2NFS60u4W7paoPE
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

