version: '3.8'

services:
  # Node.js
  app:
    build: ./api3
    ports:
      - "8003:8003"
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=ASIAVYOMUIQS4MTTCJ2F
      - AWS_SECRET_ACCESS_KEY=tbfX0Z9Ie6XQGMqPDzxHDJIqxGCy3NprSJtW7g7N
      - AWS_SESSION_TOKEN=IQoJb3JpZ2luX2VjEBEaCXVzLXdlc3QtMiJGMEQCICs4CUwJhf7J7PU5JBduRAarZJk16AtR9mabvL+kU+5zAiAVK8N616eQtTGuT7vOvQmJU46m+21GF2N4acBNwUYNTCqcAghqEAEaDDM5NjEwMzAwOTMxNyIM/cbE3YxmRuiLB0TZKvkBABhsjIu3tFj58Y2FJQiOBCcwcqVr1HbuwzD6vAbDC8yzDrH+3BbNpePIRwWD7gHIktbtixLT0nebdIb/nQEA47NlWxv6EFeMxdf24h9eUYGc+3R6eK1ufYkCtm1D4PSqQeJPIJ9IpvdSTwLWfvoft5DLZUnVoY/5rTCmntZ3ITVWg2LkCIQisja933/JmR/Yqw9EgkxJIebAEMlM2pTYvMlpjCDQB8Ua+y+5yBI8OMAPrvnSqhAgVzhlBC1xqHbIAe237Z0vxtz97JQVIEubs1xWXsxwAgAf5HKYE+aq5GxzQ7vdF4v2qAGTtiQgRHVVyyrDPS8O9iahMO+8nLgGOp4BTidYB8/IMVW2bfFR64rke5gmNhhZCNnPeb5tJNyjNVnAKiQGQuV1z4V5sJWstCDSpTTX8tYZzPY1WM52GEgd6UpYiZuqREY4PIeFUZhgkzqQKhpN6MWtnxjiKwhxES9KTu0KfaeyJ64XI/YFhLd0Pd8LkudF+7Zo515eHvOh7i3Q5gj3Qr3YtuSwXpO+VYXt0LV1ErMuVoP8yhEwZWk=
      
    networks:
      - my-network

  orquestador:
    build: ./orquestador
    ports:
      - "8001:8001"
    networks:
      - my-network

  # FastAPI
  api1:
    build: ./api1
    ports:
      - "8000:8000"
    environment:
      - DATA_USER=postgres.gwtvzmsuunpikefnnzwn
      - DATA_PASSWORD=L2NFS60u4W7paoPE
      - HOST=aws-0-us-east-1.pooler.supabase.com
      - DB_PORT=5432
      - DATABASE_NAME=bd_1
    networks:
      - my-network

  # Spring Boot
  api2:
    build: ./api2
    ports:
      - "8002:8002"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:5432/bd_2
      - SPRING_DATASOURCE_USERNAME=postgres.gwtvzmsuunpikefnnzwn
      - SPRING_DATASOURCE_PASSWORD=L2NFS60u4W7paoPE
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

