version: '3.8'

services:
  # Node.js
  app:
    build: ./api3
    ports:
      - "8003:8003"
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=ASIAVYOMUIQS57RO4N3L
      - AWS_SECRET_ACCESS_KEY=ndyYnkyenJVRA74ytREnAGG3eej6eHVffnl5ysiG
      - AWS_SESSION_TOKEN=IQoJb3JpZ2luX2VjELT//////////wEaCXVzLXdlc3QtMiJIMEYCIQDlj8NpVztG2S5BrM+xZFZnVmAZAingDEVySNHI4pI8PAIhAIRLQDcJI30dLXt5u7t5KGtZwO0Y9UGivpfJ+N1HUY8fKqUCCP3//////////wEQARoMMzk2MTAzMDA5MzE3Igza1zbFAZ3rwjzMVasq+QFiYoa+k+mJUMh+ISy7FP+OcN7OQnfTp/7pF+ZXKD53JCZDBauGSLPuexP1iPV05rebUpdpcX+octji/ttMrYMVcV5adNnHRimirAXI8L3aHSPEAwu7FC9vw286FsaxUFA8/RLFbZoQ+0l4+NijRzf5FA7DdjvONsV8T5gQ+/jDLYKCm+upIOakxDHbRBSzIIzQXv84x1XrJCUHbyTHEP4B77UIE3H+rszN5DqPvUeuP4paLMOm/AVJ6bX2eNzFi+FfYZF3VAytpKWVd2MH8SZwFa10EEnsUt9KbzEUI4BlFD/SXXw6astYYHhmyIILxXgajGqlpOA4PF8wzY+IuAY6nAHa2A0DI9rcITgCrtrNDmpymdyQZngDftqO/F+oov/8cYWxkwaN0EHaI37+Frlx0EZ6lW8YTLs3qadC821ZIzKrKhyrLuHRu5I258dCS06VX0PmWWD7Q6Wa5CXPaJogyuAjyj+epIBq1nDrwDwtlGc1Sb4bUNzWaJzdqAfT35wkSDEKYgtpDRbnqmXckPHOOXGPA4fInEpsefLw6jA=
      
    networks:
      - my-network

  orquestador:
    build: ./orquestador
    ports:
      - "8001:8001"
    networks:
      - my-network

  # FastAPI
  api1:
    build: ./api1
    ports:
      - "8000:8000"
    environment:
      - DATA_USER=postgres.gwtvzmsuunpikefnnzwn
      - DATA_PASSWORD=L2NFS60u4W7paoPE
      - HOST=aws-0-us-east-1.pooler.supabase.com
      - DB_PORT=5432
      - DATABASE_NAME=bd_1
    networks:
      - my-network

  # Spring Boot
  api2:
    build: ./api2
    ports:
      - "8002:8002"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:5432/bd_2
      - SPRING_DATASOURCE_USERNAME=postgres.gwtvzmsuunpikefnnzwn
      - SPRING_DATASOURCE_PASSWORD=L2NFS60u4W7paoPE
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

