import localFont from "next/font/local";
import Link from "next/link";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-gray-800 text-white py-4">
          <nav className="container mx-auto flex justify-between">
            <div>
              <Link href="/auth/login" className="ml-2 mr-4 hover:underline">
                Login
              </Link>
              <Link href="/auth/register" className="hover:underline">
                Register
              </Link>
              <Link href="/dashboard" className="ml-4 hover:underline">
                Dashboard
              </Link>
              <Link href="/games" className="ml-4 hover:underline">
                Games
              </Link>
            </div>
          </nav>
        </header>
        
        <main className="container mx-auto mt-8">
          {children}
        </main>
      </body>
    </html>
  );
}
